# .github/workflows/main.yml

name: Generate Contribution Graphs

on:
  # Roda a cada 12 horas
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jobs to update contribution graph

    steps:
      - uses: actions/checkout@v3

      - uses: ThaUnknown/pacman-github-profile-readme@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs_pacman: dist/pacman-contribution-graph.svg
          outputs_pacman_dark: dist/pacman-contribution-graph-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}